#!/usr/bin/env python3
"""
Test your specific LangFuse keys with a simple trace
"""
from langfuse import observe
import os

# Set your keys as environment variables
os.environ['LANGFUSE_SECRET_KEY'] = "sk-lf-9720fd8e-1370-4b4d-adcf-3c83f637ad84"
os.environ['LANGFUSE_PUBLIC_KEY'] = "pk-lf-862b860f-83d4-4537-96c1-0cfba9ce0748"
os.environ['LANGFUSE_HOST'] = "http://localhost:3001"

@observe()
def step4_agent_workflow(query: str):
    """Main AI conversation trace"""
    print(f"🎭 Processing query: {query}")
    
    # Simulate agent operations
    classification = classify_query(query)
    tools_results = execute_tools(query, classification)
    response = generate_response(query, tools_results)
    
    return {
        "message": response,
        "classification": classification,
        "tools_used": tools_results["tools_used"]
    }

@observe()
def classify_query(query: str):
    """Query classification span"""
    print("  🤖 Classifying query...")
    return {"intent": "product_search", "confidence": 0.95}

@observe()
def execute_tools(query: str, classification: dict):
    """Tool execution span"""
    print("  🔧 Executing tools...")
    return {
        "tools_used": ["search_products", "get_customer_info"],
        "results": {"products": 6, "customer": "not_found"}
    }

@observe()
def generate_response(query: str, tool_results: dict):
    """Response generation span"""  
    print("  💬 Generating response...")
    return "I found 6 iPhone products for you!"

if __name__ == "__main__":
    print("🧪 Testing Your LangFuse Keys")
    print("=" * 35)
    print(f"Host: {os.environ['LANGFUSE_HOST']}")
    print(f"Public Key: {os.environ['LANGFUSE_PUBLIC_KEY'][:20]}...")
    
    # Run traced workflow
    query = "Show me iPhone products for john.doe@email.com"
    print(f"\nQuery: {query}")
    
    result = step4_agent_workflow(query)
    
    print(f"\n✅ Workflow completed!")
    print(f"Response: {result['message']}")
    print(f"Tools Used: {result['tools_used']}")
    
    # Import and flush manually
    from langfuse import Langfuse
    
    langfuse = Langfuse(
        secret_key="sk-lf-9720fd8e-1370-4b4d-adcf-3c83f637ad84",
        public_key="pk-lf-862b860f-83d4-4537-96c1-0cfba9ce0748",
        host="http://localhost:3001"
    )
    
    print(f"\n📤 Flushing traces...")
    langfuse.flush()
    
    print(f"\n🎉 TRACES SENT!")
    print(f"🌐 Check your LangFuse dashboard: http://localhost:3001")
    print(f"   Look for these trace names:")
    print(f"   - step4_agent_workflow")
    print(f"   - classify_query") 
    print(f"   - execute_tools")
    print(f"   - generate_response")
    print(f"\n📍 Trace ID: {result.get('trace_id', 'Generated by @observe decorator')}")